= {Caibidil} 7 | {teidealNaCaibidle}
:showtitle:
:table-caption!:

== 7.1 {7-1-title}

{7-1-p1}

{7-1-p2}

=== 7.1.1 {7-1-1-title}

{7-1-1-p}

[list-[lower-alpha]]
a. {7-1-1-a-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-a-sample1_ga} | {7-1-1-a-sample1} 
| {7-1-1-a-sample2_ga} | {7-1-1-a-sample2} 
| {7-1-1-a-sample3_ga} | {7-1-1-a-sample3} 
| {7-1-1-a-sample4_ga} | {7-1-1-a-sample4} 
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-a-sample1}
| {7-1-1-a-sample2}
| {7-1-1-a-sample3}
| {7-1-1-a-sample4}
|===
endif::[]

b. {7-1-1-b-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-b-sample1_ga} | {7-1-1-b-sample1}
| {7-1-1-b-sample2_ga} | {7-1-1-b-sample2}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-b-sample1}
| {7-1-1-b-sample2}
|===
endif::[]

c. {7-1-1-c-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-c-sample1_ga} | {7-1-1-c-sample1}
| {7-1-1-c-sample2_ga} | {7-1-1-c-sample2}
| {7-1-1-c-sample3_ga} | {7-1-1-c-sample3}
| {7-1-1-c-sample4_ga} | {7-1-1-c-sample4}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-c-sample1}
| {7-1-1-c-sample2}
| {7-1-1-c-sample3}
| {7-1-1-c-sample4}
|===
endif::[]

d. {7-1-1-d-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-d-sample1_ga} | {7-1-1-d-sample1}
| {7-1-1-d-sample2_ga} | {7-1-1-d-sample2}
| {7-1-1-d-sample3_ga} | {7-1-1-d-sample3}
| {7-1-1-d-sample4_ga} | {7-1-1-d-sample4}
| {7-1-1-d-sample5_ga} | {7-1-1-d-sample5}
| {7-1-1-d-sample6_ga} | {7-1-1-d-sample6}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-d-sample1}
| {7-1-1-d-sample2}
| {7-1-1-d-sample3}
| {7-1-1-d-sample4}
| {7-1-1-d-sample5}
| {7-1-1-d-sample6}
|===
endif::[]

e. {7-1-1-e-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-e-sample1_ga} | {7-1-1-e-sample1}
| {7-1-1-e-sample2_ga} | {7-1-1-e-sample2}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-e-sample1}
| {7-1-1-e-sample2}
|===
endif::[]

f. {7-1-1-f-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-f-sample1_ga} | {7-1-1-f-sample1}
| {7-1-1-f-sample2_ga} | {7-1-1-f-sample2}
| {7-1-1-f-sample3_ga} | {7-1-1-f-sample3}
| {7-1-1-f-sample4_ga} | {7-1-1-f-sample4}
| {7-1-1-f-sample5_ga} | {7-1-1-f-sample5}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-f-sample1}
| {7-1-1-f-sample2}
| {7-1-1-f-sample3}
| {7-1-1-f-sample4}
| {7-1-1-f-sample5}
|===
endif::[]

g. {7-1-1-g-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-g-sample1_ga} | {7-1-1-g-sample1}
| {7-1-1-g-sample2_ga} | {7-1-1-g-sample2}
| {7-1-1-g-sample3_ga} | {7-1-1-g-sample3}
| {7-1-1-g-sample4_ga} | {7-1-1-g-sample4}
| {7-1-1-g-sample5_ga} | {7-1-1-g-sample5}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-g-sample1}
| {7-1-1-g-sample2}
| {7-1-1-g-sample3}
| {7-1-1-g-sample4}
| {7-1-1-g-sample5}
|===
endif::[]

h. {7-1-1-h-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-h-sample1_ga} | {7-1-1-h-sample1}
| {7-1-1-h-sample2_ga} | {7-1-1-h-sample2}
| {7-1-1-h-sample3_ga} | {7-1-1-h-sample3}
| {7-1-1-h-sample4_ga} | {7-1-1-h-sample4}
| {7-1-1-h-sample5_ga} | {7-1-1-h-sample5}
| {7-1-1-h-sample6_ga} | {7-1-1-h-sample6}
| {7-1-1-h-sample7_ga} | {7-1-1-h-sample7}
| {7-1-1-h-sample8_ga} | {7-1-1-h-sample8}
| {7-1-1-h-sample9_ga} | {7-1-1-h-sample9}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-h-sample1}
| {7-1-1-h-sample2}
| {7-1-1-h-sample3}
| {7-1-1-h-sample4}
| {7-1-1-h-sample5}
| {7-1-1-h-sample6}
| {7-1-1-h-sample7}
| {7-1-1-h-sample8}
| {7-1-1-h-sample9}
|===
endif::[]

i. {7-1-1-i-p}
+
[.samplebox]
ifndef::isGa[]
[cols="1,1"]
|===
| {7-1-1-i-sample1_ga} | {7-1-1-i-sample1}
| {7-1-1-i-sample2_ga} | {7-1-1-i-sample2}
| {7-1-1-i-sample3_ga} | {7-1-1-i-sample3}
| {7-1-1-i-sample4_ga} | {7-1-1-i-sample4}
| {7-1-1-i-sample5_ga} | {7-1-1-i-sample5}
|===
endif::[]
ifdef::isGa[]
|===
| {7-1-1-i-sample1}
| {7-1-1-i-sample2}
| {7-1-1-i-sample3}
| {7-1-1-i-sample4}
| {7-1-1-i-sample5}
|===
endif::[]

'''

== 7.2 {7-2-title}

[list-[lower-alpha]]
. {7-2-a-p}
. {7-2-b-p1}
[list-[lower-roman]]
.. {7-2-b-i-p}
.. {7-2-b-ii-p}
.. {7-2-b-iii-p}
.. {7-2-b-iv-p}

+
{7-2-b-p2}

=== 7.2.1 {7-2-1-title}

[list-[upper-alpha]]
. *{7-2-1-A-title}*
+
{7-2-1-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7A</strong> {Table7A-caption}
  </caption>
  <colgroup>
    <col class="w-3/16">
    <col class="w-3/16">
    <col class="w-10/16">
  </colgroup>
  <thead>
  <tr>
    <th colspan="3" class="text-xl py-2">{Table7A-header}</th>
  </tr>
  <tr>
    <th colspan="3">{Table7A-subheader}</th>
  </tr></thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <th>is</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7A-example1}]
ifndef::isGa[]
            {Table7A-example1_ga} <br />
            ({Table7A-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7A-example2}]
ifndef::isGa[]
            {Table7A-example2_ga} <br />
            ({Table7A-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <th>ní</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7A-example3}]
ifndef::isGa[]
            {Table7A-example3_ga} <br />
            ({Table7A-example3})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7A-example4}]
ifndef::isGa[]
            {Table7A-example4_ga} <br />
            ({Table7A-example4})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Positive}</td>
    <th>an</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7A-example5}]
ifndef::isGa[]
            {Table7A-example5_ga} <br />
            ({Table7A-example5})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7A-example6}]
ifndef::isGa[]
            {Table7A-example6_ga} <br />
            ({Table7A-example6})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Negative}</td>
    <th>nach</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7A-example7}]
ifndef::isGa[]
            {Table7A-example7_ga} <br />
            ({Table7A-example7})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7A-example8}]
ifndef::isGa[]
            {Table7A-example8_ga} <br />
            ({Table7A-example8})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

. *{7-2-1-B-title}*
+
{7-2-1-B-p1}
+
--
[list-[lower-alpha]]
.. {7-2-1-B-a-p}
.. {7-2-1-B-b-p}
+
[list-[lower-roman]]
... {7-2-1-B-b-i-p}
... {7-2-1-B-b-ii-p}
... {7-2-1-B-b-iii-p}
... {7-2-1-B-b-iv-p}
.. {7-2-1-B-c-p}
[list-[lower-roman]]
... {7-2-1-B-c-i-p}
... {7-2-1-B-c-ii-p}
... {7-2-1-B-c-iii-p}
... {7-2-1-B-c-iv-p}
.. {7-2-1-B-d-p}
--
+
{7-2-1-B-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7B</strong> {Table7B-caption}
  </caption>
  <colgroup>
    <col class="w-1/3">
    <col class="w-1/3">
    <col class="w-1/3">
  </colgroup>
  <thead>
    <tr>
      <th colspan="3" class="text-xl py-2">{Table7B-header}</th>
    </tr>
    <tr>
      <th>{BeforeConsonantQualified}</th>
      <th colspan="2">{BeforeVowelQualified}</th>
    </tr>
    <tr>
      <th class="bg-stone-300 text-black">ba</th>
      <th class="bg-stone-300 text-black">b'</th>
      <th class="bg-stone-300 text-black">ba (ab)</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7B-ba-example1}]
ifndef::isGa[]
          {Table7B-ba-example1_ga} <br />
          ({Table7B-ba-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-example2}]
ifndef::isGa[]
          {Table7B-ba-example2_ga} <br />
          ({Table7B-ba-example2})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-example3}]
ifndef::isGa[]
          {Table7B-ba-example3_ga} <br />
          ({Table7B-ba-example3})
endif::[]
          </li>
        </ul>
    </td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7B-b-example1}]
ifndef::isGa[]
          {Table7B-b-example1_ga} <br />
          ({Table7B-b-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[  {Table7B-b-example2}]
ifndef::isGa[]
            {Table7B-b-example2_ga} <br />
            ({Table7B-b-example2})
endif::[]
          </li>
          <li>
ifdef::isGa[  {Table7B-b-example3}]
ifndef::isGa[]
            {Table7B-b-example3_ga} <br />
            ({Table7B-b-example3})
endif::[]
          </li>
        </ul>
    </td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7B-ba-ab-example1}]
ifndef::isGa[]
          {Table7B-ba-ab-example1_ga} <br />
          ({Table7B-ba-ab-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-ab-example2}]
ifndef::isGa[]
          {Table7B-ba-ab-example2_ga} <br />
          ({Table7B-ba-ab-example2})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-ab-example3}]
ifndef::isGa[]
          {Table7B-ba-ab-example3_ga} <br />
          ({Table7B-ba-ab-example3})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-ab-example4}]
ifndef::isGa[]
          {Table7B-ba-ab-example4_ga} <br />
          ({Table7B-ba-ab-example4})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7B-ba-ab-example5}]
ifndef::isGa[]
          {Table7B-ba-ab-example5_ga} <br />
          ({Table7B-ba-ab-example5})
endif::[]
          </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++
+
{7-2-1-B-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7C</strong> {Table7C-caption}
  </caption>
  <thead>
  <tr>
    <th colspan="5" class="text-xl py-2">{Table7C-header}</th>
  </tr>
  <tr>
    <th></th>
    <th colspan="2">{BeforeConsonantQualified}</th>
    <th colspan="2">{BeforeVowelQualified}</th>
  </tr></thead>
<tbody>
  <tr>
    <td>{Negative}</td>
    <td class="font-bold bg-stone-300">níor</td>
    <td>
ifdef::isGa[{Table7C-Níor-example}]
ifndef::isGa[]
      {Table7C-Níor-example_ga} <br />
      ({Table7C-Níor-example})
endif::[]
    </td>
    <td class="font-bold bg-stone-300">níorbh</td>
    <td>
ifdef::isGa[{Table7C-Níorbh-example}]
ifndef::isGa[]
      {Table7C-Níorbh-example_ga} <br />
      ({Table7C-Níorbh-example})
endif::[]
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Positive}</td>
    <td class="font-bold bg-stone-300">ar</td>
    <td>
ifdef::isGa[{Table7C-Ar-example}]
ifndef::isGa[]
      {Table7C-Ar-example_ga} <br />
      ({Table7C-Ar-example})
endif::[]
    </td>
    <td class="font-bold bg-stone-300">arbh</td>
    <td>
ifdef::isGa[{Table7C-Arbh-example}]
ifndef::isGa[]
      {Table7C-Arbh-example_ga} <br />
      ({Table7C-Arbh-example})
endif::[]
    </td>
  </tr>
  <tr>
    <td>{Interrogative} {Negative}</td>
    <td class="font-bold bg-stone-300">nár</td>
    <td>
ifdef::isGa[{Table7C-Nár-example}]
ifndef::isGa[]
      {Table7C-Nár-example_ga} <br />
      ({Table7C-Nár-example})
endif::[]
    </td>
    <td class="font-bold bg-stone-300">nárbh</td>
    <td>
ifdef::isGa[{Table7C-Nárbh-example}]
ifndef::isGa[]
      {Table7C-Nárbh-example_ga} <br />
      ({Table7C-Nárbh-example})
endif::[]
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.2 {7-2-2-title}

[list-[upper-alpha]]
. *{7-2-2-A-title}*
+
{7-2-2-A-p1}
+
--
[list-[lower-alpha]]
.. {7-2-2-A-a-p}
.. {7-2-2-A-b-p}
[list-[lower-roman]]
... {7-2-2-A-b-i-p}
... {7-2-2-A-b-ii-p}
... {7-2-2-A-b-iii-p}
... {7-2-2-A-b-iv-p}
... {7-2-2-A-b-v-p}
.. {7-2-2-A-c-p}
[list-[lower-roman]]
... {7-2-2-A-c-i-p}
... {7-2-2-A-c-ii-p}
... {7-2-2-A-c-iii-p}
... {7-2-2-A-c-iv-p}
... {7-2-2-A-c-v-p}
... {7-2-2-A-c-vi-p}
--
+
{7-2-2-A-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7D</strong> {Table7D-caption}
  </caption>
  <colgroup>
    <col class="w-1/7">
    <col class="w-2/7">
    <col class="w-2/7">
    <col class="w-2/7">
  </colgroup>
  <thead>
    <tr>
        <th colspan="4" class="text-xl py-2">{Table7D-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th colspan="2">{BeforeVowel}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">gur</th>
    <th class="bg-stone-300">gur</th>
    <th class="bg-stone-300">gurb</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7D-gur-cons-example1}]
ifndef::isGa[]
            {Table7D-gur-cons-example1_ga} <br />
            ({Table7D-gur-cons-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-gur-cons-example2}]
ifndef::isGa[]
            {Table7D-gur-cons-example2_ga} <br />
            ({Table7D-gur-cons-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7D-gur-vow-example1}]
ifndef::isGa[]
            {Table7D-gur-vow-example1_ga} <br />
            ({Table7D-gur-vow-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-gur-vow-example2}]
ifndef::isGa[]
            {Table7D-gur-vow-example2_ga} <br />
            ({Table7D-gur-vow-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7D-gurb-example1}]
ifndef::isGa[]
            {Table7D-gurb-example1_ga} <br />
            ({Table7D-gurb-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-gurb-example2}]
ifndef::isGa[]
            {Table7D-gurb-example2_ga} <br />
            ({Table7D-gurb-example2})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-gurb-example3}]
ifndef::isGa[]
            {Table7D-gurb-example3_ga} <br />
            ({Table7D-gurb-example3})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-gurb-example4}]
ifndef::isGa[]
            {Table7D-gurb-example4_ga} <br />
            ({Table7D-gurb-example4})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300" colspan=3>nach</th>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td colspan=3>
        <ul>
            <li>
ifdef::isGa[{Table7D-nach-example1}]
ifndef::isGa[]
            {Table7D-nach-example1_ga} <br />
            ({Table7D-nach-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-nach-example2}]
ifndef::isGa[]
            {Table7D-nach-example2_ga} <br />
            ({Table7D-nach-example2})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-nach-example3}]
ifndef::isGa[]
            {Table7D-nach-example3_ga} <br />
            ({Table7D-nach-example3})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7D-nach-example4}]
ifndef::isGa[]
            {Table7D-nach-example4_ga} <br />
            ({Table7D-nach-example4})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

. *{7-2-2-B-title}*
+
{7-2-2-B-p}
+
[list-[lower-alpha]]
.. {7-2-2-B-a-title}
+
{7-2-2-B-a-p1}
+
--
[list-[lower-roman]]
... {7-2-2-B-a-i}
... {7-2-2-B-a-ii}
--
+
{7-2-2-B-a-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7E</strong> {Table7E-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7E-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th class="bg-stone-300"></th>
      <th class="bg-stone-300">gur</th>
      <th class="bg-stone-300">gurbh</th>
    </tr>
    <tr>
      <td>{Positive}</td>
      <td>
          <ul>
              <li>
ifdef::isGa[{Table7E-gur-example1}]
ifndef::isGa[]
              {Table7E-gur-example1_ga} <br />
              ({Table7E-gur-example1})
endif::[]
              </li>
              <li>
ifdef::isGa[{Table7E-gur-example2}]
ifndef::isGa[]
              {Table7E-gur-example2_ga} <br />
              ({Table7E-gur-example2})
endif::[]
              </li>
          </ul>
      </td>
      <td>
          <ul>
              <li>
ifdef::isGa[{Table7E-gurbh-example1}]
ifndef::isGa[]
              {Table7E-gurbh-example1_ga} <br />
              ({Table7E-gurbh-example1})
endif::[]
              </li>
              <li>
ifdef::isGa[{Table7E-gurbh-example2}]
ifndef::isGa[]
              {Table7E-gurbh-example2_ga} <br />
              ({Table7E-gurbh-example2})
endif::[]
              </li>
          </ul>
      </td>
    </tr>
  </tbody>
</table>
++++

.. {7-2-2-B-b-title}
+
{7-2-2-B-b-p1}
+
--
[list-[lower-roman]]
... {7-2-2-B-b-i}
... {7-2-2-B-b-ii}
[.list-dots]
**** {7-2-2-B-b-ii-1}
**** {7-2-2-B-b-ii-2}
**** {7-2-2-B-b-ii-3}
**** {7-2-2-B-b-ii-4}
... {7-2-2-B-b-iii}
[.list-dots]
**** {7-2-2-B-b-iii-1}
**** {7-2-2-B-b-iii-2}
**** {7-2-2-B-b-iii-3}
**** {7-2-2-B-b-iii-4}
--
+
{7-2-2-B-b-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7F</strong> {Table7F-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7F-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">go mba</th>
    <th class="bg-stone-300">go mba <span class="font-normal">{nó}</span> go mb'</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7F-go-mba-cons-example1}]
ifndef::isGa[]
            {Table7F-go-mba-cons-example1_ga} <br />
            ({Table7F-go-mba-cons-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7F-go-mba-cons-example2}]
ifndef::isGa[]
            {Table7F-go-mba-cons-example2_ga} <br />
            ({Table7F-go-mba-cons-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7F-go-mba-vow-example1}]
ifndef::isGa[]
            {Table7F-go-mba-vow-example1_ga} <br />
            ({Table7F-go-mba-vow-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7F-go-mba-vow-example2}]
ifndef::isGa[]
            {Table7F-go-mba-vow-example2_ga} <br />
            ({Table7F-go-mba-vow-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

.. {7-2-2-B-c-title}
+
{7-2-2-B-c-p1}
+
--
[list-[lower-roman]]
... {7-2-2-B-c-i}
... {7-2-2-B-c-ii}
--
+
{7-2-2-B-c-p2}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7G</strong> {Table7G-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7G-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <th class="bg-stone-300"></th>
    <th class="bg-stone-300">nár</th>
    <th class="bg-stone-300">nárbh</th>
  </tr>
  <tr>
    <td>{Positive}</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7G-nár-example1}]
ifndef::isGa[]
            {Table7G-nár-example1_ga} <br />
            ({Table7G-nár-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7G-nár-example2}]
ifndef::isGa[]
            {Table7G-nár-example2_ga} <br />
            ({Table7G-nár-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7G-nárbh-example1}]
ifndef::isGa[]
            {Table7G-nárbh-example1_ga} <br />
            ({Table7G-nárbh-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7G-nárbh-example2}]
ifndef::isGa[]
            {Table7G-nárbh-example2_ga} <br />
            ({Table7G-nárbh-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.3 {7-2-3-title}

[list-[upper-alpha]]
. *{7-2-3-A-title}*
+
{7-2-3-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7H</strong> {Table7H-caption}
  </caption>
  <colgroup>
    <col>
    <col>
    <col class="w-4/6">
  </colgroup>
  <thead>
    <tr>
        <th colspan="3" class="text-xl py-2">{Table7H-header}</th>
    </tr>
    <tr>
        <th colspan="3">{Table7H-subheader}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <th>is</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7H-is-example1}]
ifndef::isGa[]
            {Table7H-is-example1_ga} <br />
            ({Table7H-is-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7H-is-example2}]
ifndef::isGa[]
            {Table7H-is-example2_ga} <br />
            ({Table7H-is-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <th>nach</th>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7H-nach-example1}]
ifndef::isGa[]
            {Table7H-nach-example1_ga} <br />
            ({Table7H-nach-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7H-nach-example2}]
ifndef::isGa[]
            {Table7H-nach-example2_ga} <br />
            ({Table7H-nach-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

. *{7-2-3-B-title}*
+
{7-2-3-B-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7I</strong> {Table7I-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7I-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonantQualified}</th>
        <th colspan=2>{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ba</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7I-ba-example1}]
ifndef::isGa[]
            {Table7I-ba-example1_ga} <br />
            ({Table7I-ba-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7I-ba-example2}]
ifndef::isGa[]
            {Table7I-ba-example2_ga} <br />
            ({Table7I-ba-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">ab</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7I-ab-example1}]
ifndef::isGa[]
            {Table7I-ab-example1_ga} <br />
            ({Table7I-ab-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7I-ab-example2}]
ifndef::isGa[]
            {Table7I-ab-example2_ga} <br />
            ({Table7I-ab-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nár</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7I-nár-example1}]
ifndef::isGa[]
            {Table7I-nár-example1_ga} <br />
            ({Table7I-nár-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7I-nár-example2}]
ifndef::isGa[]
            {Table7I-nár-example2_ga} <br />
            ({Table7I-nár-example2})
endif::[]
            </li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">nárbh</td>
    <td>
        <ul>
            <li>
ifdef::isGa[{Table7I-nárbh-example1}]
ifndef::isGa[]
            {Table7I-nárbh-example1_ga} <br />
            ({Table7I-nárbh-example1})
endif::[]
            </li>
            <li>
ifdef::isGa[{Table7I-nárbh-example2}]
ifndef::isGa[]
            {Table7I-nárbh-example2_ga} <br />
            ({Table7I-nárbh-example2})
endif::[]
            </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.4 {7-2-4-title}

[list-[upper-alpha]]
. *{7-2-4-A-title}*
+
{7-2-4-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7J</strong> {Table7J-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7J-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan=2>{BeforeConsonant}</th>
        <th colspan=2>{BeforeVowel}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ar</td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7J-ar-example1}]
ifndef::isGa[]
        {Table7J-ar-example1_ga} <br />
        ({Table7J-ar-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7J-ar-example2}]
ifndef::isGa[]
        {Table7J-ar-example2_ga} <br />
        ({Table7J-ar-example2})
endif::[]
          </li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">arb</td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7J-arb-example1}]
ifndef::isGa[]
        {Table7J-arb-example1_ga} <br />
        ({Table7J-arb-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7J-arb-example2}]
ifndef::isGa[]
        {Table7J-arb-example2_ga} <br />
        ({Table7J-arb-example2})
endif::[]
          </li>
        </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7J-nach-example1}]
ifndef::isGa[]
          {Table7J-nach-example1_ga} <br />
          ({Table7J-nach-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7J-nach-example2}]
ifndef::isGa[]
          {Table7J-nach-example2_ga} <br />
          ({Table7J-nach-example2})
endif::[]
          </li>
        </ul>
    </td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
        <ul>
          <li>
ifdef::isGa[{Table7J-nach-example3}]
ifndef::isGa[]
          {Table7J-nach-example3_ga} <br />
          ({Table7J-nach-example3})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7J-nach-example4}]
ifndef::isGa[]
          {Table7J-nach-example4_ga} <br />
          ({Table7J-nach-example4})
endif::[]
          </li>
        </ul>
    </td>
  </tr>
</tbody>
</table>
++++

. *{7-2-4-B-title}*
+
{7-2-4-B-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7K</strong> {Table7K-caption}
  </caption>
  <thead>
    <tr>
        <th colspan="5" class="text-xl py-2">{Table7K-header}</th>
    </tr>
    <tr>
        <th></th>
        <th colspan="2">{BeforeConsonantQualified}</th>
        <th colspan="2">{BeforeVowelQualified}</th>
    </tr>
  </thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <td class="bg-stone-300 font-bold">ar</td>
    <td>
ifdef::isGa[{Table7K-ar-example}]
ifndef::isGa[]
      {Table7K-ar-example_ga} <br />
      ({Table7K-ar-example})
endif::[]
    </td>
    <td class="bg-stone-300 font-bold">arbh</td>
    <td>
ifdef::isGa[{Table7K-arbh-example}]
ifndef::isGa[]
        {Table7K-arbh-example_ga} <br />
        ({Table7K-arbh-example})
endif::[]
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <td class="bg-stone-300 font-bold">nach</td>
    <td>
ifdef::isGa[{Table7K-nár-example}]
ifndef::isGa[]
        {Table7K-nár-example_ga} <br />
        ({Table7K-nár-example})
endif::[]
    </td>
    <td class="bg-stone-300 font-bold">nárbh</td>
    <td>
ifdef::isGa[{Table7K-nárbh-example}]
ifndef::isGa[]
        {Table7K-nárbh-example_ga} <br />
        ({Table7K-nárbh-example})
endif::[]
    </td>
  </tr>
</tbody>
</table>
++++

=== 7.2.5 {7-2-5-title}

[list-[upper-alpha]]
. *{7-2-5-A-title}*
+
[list-[lower-alpha]]
.. {7-2-5-A-a-p}
[list-[lower-roman]]
... {7-2-5-A-a-i-p}
... {7-2-5-A-a-ii-p}
... {7-2-5-A-a-iii-p}

.. {7-2-5-A-b-p}
[list-[lower-roman]]
... {7-2-5-A-b-i-p}
... {7-2-5-A-b-ii-p}
... {7-2-5-A-b-iii-p}
... {7-2-5-A-b-iv-p}
... {7-2-5-A-b-v-p}
... {7-2-5-A-b-vi-p}

.. {7-2-5-A-c-p}
+
--
[list-[lower-roman]]
... {7-2-5-A-c-i-p}
... {7-2-5-A-c-ii-p}
... {7-2-5-A-c-iii-p}
--
+
{7-2-5-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7L</strong> {Table7L-caption}
  </caption>
  <colgroup>
    <col style="width: 50%"/>
    <col style="width: 50%"/>
  </colgroup>
  <thead>
    <tr>
        <th colspan="2" class="text-xl font-bold">{Table7L-header}</th>
    </tr>
    <tr>
        <th>{Table7L-subheader-col1}</th>
        <th>{Table7L-subheader-col2}</th>
    </tr></thead>
<tbody>
  <tr>
    <td>{Table7L-row1-col1}</td>
    <td>{Table7L-row1-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row2-col1}</td>
    <td>{Table7L-row2-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row3-col1}</td>
    <td>{Table7L-row3-col2}</td>
  </tr>
  <tr>
    <td>{Table7L-row4-col1}</td>
    <td></td>
  </tr>
  <tr>
    <td>{Table7L-row5-col1}</td>
    <td></td>
  </tr>
  <tr>
    <td>{Table7L-row6-col1}</td>
    <td></td>
  </tr>
</tbody>
</table>
++++

. *{7-2-5-B-title}*
+
{7-2-5-B-p}

'''

== 7.3 {7-3-title}

=== 7.3.1 {7-3-1-title}

[list-[upper-alpha]]
. *{7-3-1-A-title}*
+
{7-3-1-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7M</strong> {Table7M-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7M-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
<tbody>
  <tr>
    <th>cá</th>
    <td>
ifdef::isGa[{Table7M-Cá-example}]
ifndef::isGa[]
      {Table7M-Cá-example_ga} <br />
      ({Table7M-Cá-example})
endif::[]
    </td>
    <td>
ifdef::isGa[{Table7M-Cárb-example}]
ifndef::isGa[]
      {Table7M-Cárb-example_ga} <br />
      ({Table7M-Cárb-example})
endif::[]
    </td>
  </tr>
  <tr>
    <th>cé</th>
    <td>
ifdef::isGa[{Table7M-Cé-example}]
ifndef::isGa[]
      {Table7M-Cé-example_ga} <br />
      ({Table7M-Cé-example})
endif::[]
    </td>
    <td>
ifdef::isGa[{Table7M-Cérb-example}]
ifndef::isGa[]
      {Table7M-Cérb-example_ga} <br />
      ({Table7M-Cérb-example})
endif::[]
    </td>
  </tr>
</tbody>
</table>
++++

. *{7-3-1-B-title}*
+
{7-3-1-B-p1}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7N</strong> {Table7N-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7N-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
<tbody>
  <tr>
    <th>cá</th>
    <td>
ifdef::isGa[{Table7N-example1}]
ifndef::isGa[]
      {Table7N-example1_ga} <br />
      ({Table7N-example1})
endif::[]
    </td>
    <td>
ifdef::isGa[{Table7N-example2}]
ifndef::isGa[]
      {Table7N-example2_ga} <br />
      ({Table7N-example2})
endif::[]
    </td>
  </tr>
  <tr>
    <th>cé</th>
    <td>
ifdef::isGa[{Table7N-example3}]
ifndef::isGa[]
      {Table7N-example3_ga} <br />
      ({Table7N-example3})
endif::[]
    </td>
    <td>
ifdef::isGa[{Table7N-example4}]
ifndef::isGa[]
      {Table7N-example4_ga} <br />
      ({Table7N-example4})
endif::[]
    </td>
  </tr>
</tbody>
</table>
++++
+
{7-3-1-p}

=== 7.3.2 {7-3-2-title}

[list-[upper-alpha]]
. *{7-3-2-A-title}*
+
{7-3-2-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7O</strong> {Table7O-caption}
  </caption>
  <colgroup>
    <col class="w-20">
  </colgroup>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7O-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
<tbody>
    <tr>
        <th>de/do</th>
        <td>
ifdef::isGa[{Table7O-dar-example}]
ifndef::isGa[]
        {Table7O-dar-example_ga} <br />
        ({Table7O-dar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-darb-example}]
ifndef::isGa[]
        {Table7O-darb-example_ga} <br />
        ({Table7O-darb-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>faoi</th>
        <td>
ifdef::isGa[{Table7O-faoinar-example}]
ifndef::isGa[]
        {Table7O-faoinar-example_ga} <br />
        ({Table7O-faoinar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-faoinarb-example}]
ifndef::isGa[]
        {Table7O-faoinarb-example_ga} <br />
        ({Table7O-faoinarb-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>i</th>
        <td>
ifdef::isGa[{Table7O-inar-example}]
ifndef::isGa[]
        {Table7O-inar-example_ga} <br />
        ({Table7O-inar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-inarb-example}]
ifndef::isGa[]
        {Table7O-inarb-example_ga} <br />
        ({Table7O-inarb-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>le</th>
        <td>
ifdef::isGa[{Table7O-lenar-example}]
ifndef::isGa[]
        {Table7O-lenar-example_ga} <br />
        ({Table7O-lenar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-lenarb-example}]
ifndef::isGa[]
        {Table7O-lenarb-example_ga} <br />
        ({Table7O-lenarb-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>ó</th>
        <td>
ifdef::isGa[{Table7O-ónar-example}]
ifndef::isGa[]
        {Table7O-ónar-example_ga} <br />
        ({Table7O-ónar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-ónarb-example}]
ifndef::isGa[]
        {Table7O-ónarb-example_ga} <br />
        ({Table7O-ónarb-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>trí</th>
        <td>
ifdef::isGa[{Table7O-trínar-example}]
ifndef::isGa[]
        {Table7O-trínar-example_ga} <br />
        ({Table7O-trínar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7O-trínarb-example}]
ifndef::isGa[]
        {Table7O-trínarb-example_ga} <br />
        ({Table7O-trínarb-example})
endif::[]
        </td>
    </tr>
</tbody>
</table>
++++

. *{7-3-2-B-title}*
+
{7-3-2-B-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7P</strong> {Table7P-caption}
  </caption>
  <colgroup>
    <col class="w-20">
  </colgroup>
  <thead>
    <tr>
        <th colspan=3 class="text-xl font-bold">{Table7P-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
  <tbody>
    <tr>
        <th>de/do</th>
        <td>
ifdef::isGa[{Table7P-dar-example}]
ifndef::isGa[]
        {Table7P-dar-example_ga} <br />
        ({Table7P-dar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-darbh-example}]
ifndef::isGa[]
        {Table7P-darbh-example_ga} <br />
        ({Table7P-darbh-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>faoi</th>
        <td>
ifdef::isGa[{Table7P-faoinar-example}]
ifndef::isGa[]
        {Table7P-faoinar-example_ga} <br />
        ({Table7P-faoinar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-faoinarbh-example}]
ifndef::isGa[]
        {Table7P-faoinarbh-example_ga} <br />
        ({Table7P-faoinarbh-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>i</th>
        <td>
ifdef::isGa[{Table7P-inar-example}]
ifndef::isGa[]
        {Table7P-inar-example_ga} <br />
        ({Table7P-inar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-inarbh-example}]
ifndef::isGa[]
        {Table7P-inarbh-example_ga} <br />
        ({Table7P-inarbh-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>le</th>
        <td>
ifdef::isGa[{Table7P-lenar-example}]
ifndef::isGa[]
        {Table7P-lenar-example_ga} <br />
        ({Table7P-lenar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-lenarbh-example}]
ifndef::isGa[]
        {Table7P-lenarbh-example_ga} <br />
        ({Table7P-lenarbh-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>ó</th>
        <td>
ifdef::isGa[{Table7P-ónar-example}]
ifndef::isGa[]
        {Table7P-ónar-example_ga} <br />
        ({Table7P-ónar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-ónarbh-example}]
ifndef::isGa[]
        {Table7P-ónarbh-example_ga} <br />
        ({Table7P-ónarbh-example})
endif::[]
        </td>
    </tr>
    <tr>
        <th>trí</th>
        <td>
ifdef::isGa[{Table7P-trínar-example}]
ifndef::isGa[]
        {Table7P-trínar-example_ga} <br />
        ({Table7P-trínar-example})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7P-trínarbh-example}]
ifndef::isGa[]
        {Table7P-trínarbh-example_ga} <br />
        ({Table7P-trínarbh-example})
endif::[]
        </td>
    </tr>
  </tbody>
</table>
++++

=== 7.3.3 {7-3-3-title}

[list-[upper-alpha]]
. *{7-3-3-A-title}*
+
{7-3-3-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7Q</strong> {Table7Q-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3 class="text-xl py-2">{Table7Q-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonant}</th>
        <th>{BeforeVowel}</th>
    </tr></thead>
  <tbody>
    <tr>
        <th>sula</th>
        <td>
ifdef::isGa[{Table7Q-example1}]
ifndef::isGa[]
          {Table7Q-example1_ga} <br />
          ({Table7Q-example1})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7Q-example2}]
ifndef::isGa[]
          {Table7Q-example2_ga} <br />
          ({Table7Q-example2})
endif::[]
        </td>
    </tr>
    <tr>
        <th>ó</th>
        <td>
ifdef::isGa[{Table7Q-example3}]
ifndef::isGa[]
          {Table7Q-example3_ga} <br />
          ({Table7Q-example3})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7Q-example4}]
ifndef::isGa[]
          {Table7Q-example4_ga} <br />
          ({Table7Q-example4})
endif::[]
        </td>
    </tr>
  </tbody>
</table>
++++

. *{7-3-3-B-title}*
+
{7-3-3-B-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7R</strong> {Table7R-caption}
  </caption>
  <thead>
    <tr>
        <th colspan=3>{Table7R-header}</th>
    </tr>
    <tr>
        <th></th>
        <th>{BeforeConsonantQualified}</th>
        <th>{BeforeVowelQualified}</th>
    </tr></thead>
  <tbody>
    <tr>
        <th>sula</th>
        <td>
ifdef::isGa[{Table7R-example1}]
ifndef::isGa[]
        {Table7R-example1_ga} <br />
        ({Table7R-example1})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7R-example2}]
ifndef::isGa[]
        {Table7R-example2_ga} <br />
        ({Table7R-example2})
endif::[]
        </td>
    </tr>
    <tr>
        <th>ó</th>
        <td>
ifdef::isGa[{Table7R-example3}]
ifndef::isGa[]
        {Table7R-example3_ga} <br />
        ({Table7R-example3})
endif::[]
        </td>
        <td>
ifdef::isGa[{Table7R-example4}]
ifndef::isGa[]
        {Table7R-example4_ga} <br />
        ({Table7R-example4})
endif::[]
        </td>
    </tr>
  </tbody>
</table>
++++

=== 7.3.4 {7-3-4-title}

{7-3-4-p}

[list-[upper-alpha]]
. *{7-3-4-A-title}*
+
{7-3-4-A-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7S</strong> {Table7S-caption}
  </caption>
  <thead>
    <tr>
      <th colspan=5 class="text-xl py-2">{Table7S-header}</th>
    </tr>
    <tr>
      <th></th>
      <th colspan=2>{BeforeConsonant}</th>
      <th colspan=2>{BeforeVowel}</th>
    </tr></thead>
  <tbody>
    <tr>
      <td>{Positive}</td>
      <th>más</th>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7S-Más-example1}]
ifndef::isGa[]
          {Table7S-Más-example1_ga} <br />
          ({Table7S-Más-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7S-Más-example2}]
ifndef::isGa[]
          {Table7S-Más-example2_ga} <br />
          ({Table7S-Más-example2})
endif::[]
          </li>
        </ul>
      </td>
      <th>más</th>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7S-más-example3}]
ifndef::isGa[]
          {Table7S-más-example3_ga} <br />
          ({Table7S-más-example3})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7S-Más-example4}]
ifndef::isGa[]
          {Table7S-Más-example4_ga} <br />
          ({Table7S-Más-example4})
endif::[]
          </li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>{Negative}</td>
      <th>mura</th>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7S-Mura-example1}]
ifndef::isGa[]
          {Table7S-Mura-example1_ga} <br />
          ({Table7S-Mura-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7S-mura-example2}]
ifndef::isGa[]
          {Table7S-mura-example2_ga} <br />
          ({Table7S-mura-example2})
endif::[]
          </li>
        </ul>
      </td>
      <th>murab</th>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7S-murab-example1}]
ifndef::isGa[]
          {Table7S-murab-example1_ga} <br />
          ({Table7S-murab-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7S-Murab-example2}]
ifndef::isGa[]
          {Table7S-Murab-example2_ga} <br />
          ({Table7S-Murab-example2})
endif::[]
          </li>
        </ul>
      </td>
    </tr>
  </tbody>
</table>
++++

. *{7-3-4-B-title}*
+
{7-3-4-B-p}
+
[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7T</strong> {Table7T-caption}
  </caption>
  <thead>
  <tr>
    <th colspan=4 class="text-xl py-2">{Table7T-header}</th>
  </tr>
  <tr>
    <th></th>
    <th>{BeforeConsonantQualified}</th>
    <th colspan=2>{BeforeVowelQualified}</th>
  </tr></thead>
<tbody>
    <tr>
      <th></th>
      <th>má ba</th>
      <th>má b'</th>
      <th>má ba</th>
    </tr>
    <tr>
      <td>{Positive}</td>
      <td>
ifdef::isGa[{Table7T-positive-example1}]
ifndef::isGa[]
        {Table7T-positive-example1_ga} <br />
        ({Table7T-positive-example1})
endif::[]
      </td>
      <td>
ifdef::isGa[{Table7T-positive-example2}]
ifndef::isGa[]
        {Table7T-positive-example2_ga} <br />
        ({Table7T-positive-example2})
endif::[]
      </td>
      <td>
ifdef::isGa[{Table7T-positive-example3}]
ifndef::isGa[]
        {Table7T-positive-example3_ga} <br />
        ({Table7T-positive-example3})
endif::[]
      </td>
    </tr>
    <tr>
      <th></th>
      <th>murar</th>
      <th colspan=2>murarbh</th>
    </tr>
    <tr>
      <td>{Negative}</td>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7T-negative-example1}]
ifndef::isGa[]
          {Table7T-negative-example1_ga} <br />
          ({Table7T-negative-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7T-negative-example2}]
ifndef::isGa[]
          {Table7T-negative-example2_ga} <br />
          ({Table7T-negative-example2})
endif::[]
          </li>
        </ul>
      </td>
      <td colspan=2>
        <ul>
          <li>
ifdef::isGa[{Table7T-negative-example3}]
ifndef::isGa[]
          {Table7T-negative-example3_ga} <br />
          ({Table7T-negative-example3})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7T-negative-example4}]
ifndef::isGa[]
          {Table7T-negative-example4_ga} <br />
          ({Table7T-negative-example4})
endif::[]
          </li>
        </ul>
      </td>
    </tr>
</tbody>
</table>
++++

=== 7.3.5 {7-3-5-title}

{7-3-5-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7U</strong> {Table7U-caption}
  </caption>
  <thead>
    <tr>
      <th colspan=2 class="text-xl py-2">{Table7U-header}</th>
    </tr>
    <tr>
      <th colspan=2>{BeforeConsonantAndVowel}</th>
    </tr></thead>
<tbody>
    <tr>
      <th>
        Dá + ba &rarr; Dá mba <span class="font-normal">{nó}</span> Dá mb'
      </th>
      <td>
        <ul>
          <li>
ifdef::isGa[{Table7U-example1}]
ifndef::isGa[]
          {Table7U-example1_ga} <br />
          ({Table7U-example1})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7U-example2}]
ifndef::isGa[]
          {Table7U-example2_ga} <br />
          ({Table7U-example2})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7U-example3}]
ifndef::isGa[]
          {Table7U-example3_ga} <br />
          ({Table7U-example3})
endif::[]
          </li>
          <li>
ifdef::isGa[{Table7U-example4}]
ifndef::isGa[]
          {Table7U-example4_ga} <br />
          ({Table7U-example4})
endif::[]
          </li>
        </ul>
      </td>
    </tr>
</tbody>
</table>
++++

'''

== 7.4 {7-4-title}

{7-4-p}

[subs="attributes,replacements,macros"]
++++
<table class="chapter-7">
  <caption>
    <strong>{Tábla} 7V</strong> {Table7V-caption}
  </caption>
  <thead>
    <tr>
      <th colspan=5 class="text-xl py-2">{Table7V-header}</th>
    </tr>
    <tr>
      <th></th>
      <th colspan=2>{BeforeConsonant}</th>
      <th colspan=2>{BeforeVowel}</th>
    </tr></thead>
<tbody>
  <tr>
    <td>{Positive}</td>
    <th>gura</th>
    <td>
      <ul>
        <li>
ifdef::isGa[{Table7V-Gura-example1_ga}]
ifndef::isGa[]
        {Table7V-Gura-example1_ga} <br />
        ({Table7V-Gura-example1})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Gura-example2_ga}]
ifndef::isGa[]
        {Table7V-Gura-example2_ga} <br />
        ({Table7V-Gura-example2})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Gura-example3_ga}]
ifndef::isGa[]
        {Table7V-Gura-example3_ga} <br />
        ({Table7V-Gura-example3})
endif::[]
        </li>
      </ul>
    </td>
    <th class="bg-stone-300">gurab</th>
    <td>
      <ul>
        <li>
ifdef::isGa[{Table7V-Gurab-example1_ga}]
ifndef::isGa[]
        {Table7V-Gurab-example1_ga} <br />
        ({Table7V-Gurab-example1})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Gurab-example2_ga}]
ifndef::isGa[]
        {Table7V-Gurab-example2_ga} <br />
        ({Table7V-Gurab-example2})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Gurab-example3_ga}]
ifndef::isGa[]
        {Table7V-Gurab-example3_ga} <br />
        ({Table7V-Gurab-example3})
endif::[]
        </li>
      </ul>
    </td>
  </tr>
  <tr>
    <td>{Negative}</td>
    <th class="bg-stone-300">nára</th>
    <td>
      <ul>
        <li>
ifdef::isGa[{Table7V-Nára-example1_ga}]
ifndef::isGa[]
        {Table7V-Nára-example1_ga} <br />
        ({Table7V-Nára-example1})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Nára-example2_ga}]
ifndef::isGa[]
        {Table7V-Nára-example2_ga} <br />
        ({Table7V-Nára-example2})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Nára-example3_ga}]
ifndef::isGa[]
        {Table7V-Nára-example3_ga} <br />
        ({Table7V-Nára-example3})
endif::[]
        </li>
      </ul>
    </td>
    <th>nárab</th>
    <td>
      <ul>
        <li>
ifdef::isGa[{Table7V-Nárab-example1_ga}]
ifndef::isGa[]
        {Table7V-Nárab-example1_ga} <br />
        ({Table7V-Nárab-example1})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Nárab-example2_ga}]
ifndef::isGa[]
        {Table7V-Nárab-example2_ga} <br />
        ({Table7V-Nárab-example2})
endif::[]
        </li>
        <li>
ifdef::isGa[{Table7V-Nárab-example3_ga}]
ifndef::isGa[]
        {Table7V-Nárab-example3_ga} <br />
        ({Table7V-Nárab-example3})
endif::[]
        </li>
      </ul>
    </td>
  </tr>
</tbody>
</table>
++++
